// Missions, based on the SCDF Civil Defence Emergency Handbook (10th ed., 2026)
// and NEA haze advisories.
// Types: checklist (tick every step), quiz (get every answer right),
// action (done elsewhere in the app, e.g. adding a map pin).

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'haze', label: 'Haze' },
  { id: 'flood', label: 'Flood' },
  { id: 'fire', label: 'Fire' },
  { id: 'firstaid', label: 'First aid' },
  { id: 'essentials', label: 'Essentials' },
];

export const MISSIONS = [
  {
    id: 'emergency-numbers',
    title: 'Learn emergency numbers',
    category: 'essentials',
    type: 'quiz',
    xp: 20,
    source: 'SCDF Civil Defence Emergency Handbook',
    summary: 'Know who to call, and when, before you ever need to.',
    guideId: 'first-aid',
    questions: [
      {
        id: 'q1',
        prompt: 'Which number do you call for a fire or a medical emergency?',
        options: ['995', '999', '1777', '1800 280 0000'],
        answer: 0,
        explain: '995 reaches SCDF for fire, rescue and emergency ambulance.',
      },
      {
        id: 'q2',
        prompt: 'Which number do you call for the Police?',
        options: ['995', '999', '1777', '1800 752 1800'],
        answer: 1,
        explain: '999 is the Police emergency line.',
      },
      {
        id: 'q3',
        prompt: 'Which number is for a non-emergency ambulance?',
        options: ['995', '999', '1777', '1800 342 5222'],
        answer: 2,
        explain: 'Call 1777 for non-emergency ambulance services. Keep 995 free for emergencies.',
      },
      {
        id: 'q4',
        prompt: 'You smell gas from a gas pipe after a tremor. Which number do you call to report it?',
        options: ['1800 752 1800', '999', '1777', '1800 342 5222'],
        answer: 0,
        explain: 'The handbook lists 1800 752 1800 for reporting a gas pipe leakage.',
      },
    ],
  },
  {
    id: 'ready-bag',
    title: 'Pack your Ready Bag',
    category: 'essentials',
    type: 'checklist',
    xp: 80,
    source: 'SCDF Civil Defence Emergency Handbook, Ready Bag',
    summary: 'A Ready Bag holds what you need if you have to leave home in an emergency.',
    guideId: 'ready-bag',
    steps: [
      { id: 's1', text: 'Torchlight, stored without batteries inside' },
      { id: 's2', text: 'Spare batteries, packed separately so they do not leak or rust' },
      { id: 's3', text: 'Essential personal medication and healthcare supplies for your family' },
      { id: 's4', text: 'A whistle to call for help without tiring yourself or breathing in smoke' },
      { id: 's5', text: 'A first aid kit' },
      { id: 's6', text: 'Childcare and special care items for anyone who needs them' },
      { id: 's7', text: 'N95 masks for everyone in the household' },
      { id: 's8', text: 'Keep the bag somewhere easy to reach in the dark and tell everyone where it is' },
    ],
  },
  {
    id: 'haze-checklist',
    title: 'Haze preparedness checklist',
    category: 'haze',
    type: 'checklist',
    xp: 50,
    source: 'NEA haze advisories',
    summary: 'Get ready before the next haze season so you can protect vulnerable family members.',
    guideId: 'haze',
    steps: [
      { id: 's1', text: 'Keep a supply of N95 masks at home and check they are in good condition' },
      { id: 's2', text: 'Know how to put on an N95 mask with a tight seal' },
      { id: 's3', text: 'Bookmark haze.gov.sg or install the myENV app to check PSI and PM2.5' },
      { id: 's4', text: 'Keep enough medication for family members with heart or lung conditions' },
      { id: 's5', text: 'Pick a room at home you can keep closed during haze' },
      { id: 's6', text: 'Plan to check on elderly relatives and neighbours' },
    ],
  },
  {
    id: 'haze-quiz',
    title: 'Read the haze numbers',
    category: 'haze',
    type: 'quiz',
    xp: 30,
    source: 'NEA haze advisories',
    summary: 'Learn which reading to check and what each PSI band means.',
    guideId: 'haze',
    questions: [
      {
        id: 'q1',
        prompt: 'You want to go for a run in the next hour. Which reading should you check?',
        options: ['1-hr PM2.5', '24-hr PSI', 'Yesterday\u2019s PSI', 'The 4-day weather outlook'],
        answer: 0,
        explain: 'The 1-hr PM2.5 reflects current air quality, so it suits decisions about the next hour.',
      },
      {
        id: 'q2',
        prompt: 'The 24-hr PSI is 150. Which band is that?',
        options: ['Moderate', 'Unhealthy', 'Very unhealthy', 'Hazardous'],
        answer: 1,
        explain: '101 to 200 is the Unhealthy band.',
      },
      {
        id: 'q3',
        prompt: 'At a 24-hr PSI of 150, what should healthy people do?',
        options: [
          'Nothing different',
          'Reduce prolonged or strenuous outdoor exertion',
          'Avoid all outdoor activity',
          'Stay indoors with an N95 mask on',
        ],
        answer: 1,
        explain: 'In the Unhealthy band, healthy people should reduce prolonged or strenuous outdoor exertion.',
      },
    ],
  },
  {
    id: 'flood-checklist',
    title: 'Flood preparedness checklist',
    category: 'flood',
    type: 'checklist',
    xp: 50,
    source: 'SCDF Civil Defence Emergency Handbook, Floods',
    summary: 'Flash floods happen fast. Know what to do before the water rises.',
    guideId: 'floods',
    steps: [
      { id: 's1', text: 'Follow PUB\u2019s flood alert channels for rainfall and flood updates' },
      { id: 's2', text: 'Know the way to higher ground from your home, away from streams and drains' },
      { id: 's3', text: 'Keep your Ready Bag where you can grab it if told to evacuate' },
      { id: 's4', text: 'Remember: never walk through moving water higher than your ankles' },
      { id: 's5', text: 'Remember: never drive through water above kerb height or where road markings are hidden' },
    ],
  },
  {
    id: 'fire-safety',
    title: 'Home fire safety check',
    category: 'fire',
    type: 'checklist',
    xp: 60,
    source: 'SCDF Civil Defence Emergency Handbook, Fire Safety',
    summary: 'Most home fires are preventable. Check your home and your escape route.',
    guideId: 'fire',
    steps: [
      { id: 's1', text: 'Install a Home Fire Alarm Device (HFAD) and test it' },
      { id: 's2', text: 'Keep at least one certified dry chemical powder fire extinguisher at home' },
      { id: 's3', text: 'Keep corridors clear with at least a 1.2 m escape passage' },
      { id: 's4', text: 'Charge PMDs and PABs away from exits and never unattended overnight' },
      { id: 's5', text: 'Agree an escape plan with your household' },
      { id: 's6', text: 'Know the rule: evacuate if you are on the fire floor or up to two floors above it' },
    ],
  },
  {
    id: 'first-aid-kit',
    title: 'Check your first aid kit',
    category: 'firstaid',
    type: 'checklist',
    xp: 40,
    source: 'SCDF Civil Defence Emergency Handbook, First Aid Kit',
    summary: 'Every household should have a first aid kit that is stocked and in date.',
    guideId: 'first-aid',
    steps: [
      { id: 's1', text: 'Tweezers and scissors' },
      { id: 's2', text: 'A thermometer' },
      { id: 's3', text: 'Disposable gloves' },
      { id: 's4', text: 'Adhesive tape, dressings and plasters' },
      { id: 's5', text: 'Triangular and crepe bandages' },
      { id: 's6', text: 'Check expiry dates and replace used or expired items' },
      { id: 's7', text: 'Store it where adults can reach it easily but children cannot' },
    ],
  },
  {
    id: 'cpr-basics',
    title: 'Learn CPR-AED basics',
    category: 'firstaid',
    type: 'quiz',
    xp: 100,
    source: 'SCDF Civil Defence Emergency Handbook, CPR and AED',
    summary: 'CPR and an AED can restart a heart. Learn the sequence here, then train in person.',
    guideId: 'first-aid',
    questions: [
      {
        id: 'q1',
        prompt: 'Someone collapses. What do you do first?',
        options: [
          'Check if they respond',
          'Start chest compressions straight away',
          'Give them water',
          'Move them to a sofa',
        ],
        answer: 0,
        explain: 'Start by checking responsiveness, then call 995 and get someone to fetch an AED.',
      },
      {
        id: 'q2',
        prompt: 'They do not respond. What next?',
        options: [
          'Call 995 and get someone to bring an AED',
          'Wait five minutes to see if they wake',
          'Drive them to hospital',
          'Post on social media for help',
        ],
        answer: 0,
        explain: '995 specialists can also guide you through CPR over the phone.',
      },
      {
        id: 'q3',
        prompt: 'They are not breathing. What is one CPR cycle?',
        options: [
          '30 chest compressions, then 2 breaths',
          '5 compressions, then 1 breath',
          '2 breaths only',
          '10 back blows',
        ],
        answer: 0,
        explain: 'Repeat 30 compressions and 2 breaths until an AED or the ambulance crew arrives, or the casualty shows signs of life. Hands-only CPR is also an option.',
      },
      {
        id: 'q4',
        prompt: 'Where can you find an AED in many HDB estates?',
        options: [
          'At a Lifesavers\u2019 Emergency Point in the lift lobby',
          'Inside the rubbish chute room',
          'Only in hospitals',
          'At the MRT ticket machine',
        ],
        answer: 0,
        explain: 'SCDF is installing Lifesavers\u2019 Emergency Points, each with an AED and a fire extinguisher, at the lift lobby of every two HDB blocks.',
      },
    ],
  },
  {
    id: 'pws-signals',
    title: 'Know the warning signals',
    category: 'essentials',
    type: 'quiz',
    xp: 40,
    source: 'SCDF Civil Defence Emergency Handbook, Public Warning System',
    summary: 'Learn what the Public Warning System sirens and SG Alert mean.',
    guideId: 'warnings',
    questions: [
      {
        id: 'q1',
        prompt: 'You hear wailing siren blasts. What does it mean?',
        options: [
          'Alarm: move to a Civil Defence shelter immediately',
          'All clear: leave the shelter',
          'Important message: tune in to the radio',
          'A fire drill in your block',
        ],
        answer: 0,
        explain: 'The Alarm signal means an air raid or danger is approaching.',
      },
      {
        id: 'q2',
        prompt: 'You hear pulsating blasts. What should you do?',
        options: [
          'Tune in to local radio, TV and mobile notifications',
          'Move to a shelter',
          'Leave the shelter',
          'Ignore it',
        ],
        answer: 0,
        explain: 'This is the Important Message signal. It is usually sounded on 15 February and 15 September each year.',
      },
      {
        id: 'q3',
        prompt: 'An SG Alert appears full-screen on your phone. What should you do?',
        options: [
          'Stop, read it carefully and follow the instructions',
          'Dismiss it and check later',
          'Forward it to every group chat first',
          'Restart your phone',
        ],
        answer: 0,
        explain: 'SG Alerts are only sent when you need to take immediate action to stay safe.',
      },
    ],
  },
  {
    id: 'power-outage',
    title: 'Prepare for a power outage',
    category: 'essentials',
    type: 'checklist',
    xp: 40,
    source: 'SCDF Civil Defence Emergency Handbook, Power Outages',
    summary: 'Be ready to see, stay informed and stay calm when the lights go out.',
    guideId: 'power',
    steps: [
      { id: 's1', text: 'Pack a torchlight and spare batteries in your Ready Bag' },
      { id: 's2', text: 'Keep a portable power bank charged' },
      { id: 's3', text: 'Find the Essential Maintenance Service Unit (EMSU) number at your lift lobby' },
      { id: 's4', text: 'Remember: if trapped in a lift, press the alarm and wait; never force the doors' },
    ],
  },
  {
    id: 'map-resource',
    title: 'Tag a nearby emergency resource',
    category: 'essentials',
    type: 'action',
    xp: 30,
    source: 'Community map',
    summary: 'Add an AED, shelter or assembly area you have seen near you to the map.',
    action: { label: 'Open the map', href: '/map' },
  },
];

export const missionById = (id) => MISSIONS.find((m) => m.id === id);

export const TOTAL_MISSION_XP = MISSIONS.reduce((sum, m) => sum + m.xp, 0);

// Every quiz question, for the daily challenge.
export const DAILY_POOL = MISSIONS.filter((m) => m.type === 'quiz').flatMap((m) =>
  m.questions.map((q) => ({ ...q, missionId: m.id, key: `${m.id}:${q.id}` }))
);
